version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | -E bash -
      - apt install -y nodejs
pre_build:
  commands:
    - npm
build:
  commands:
    - npm build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist